# 站点基本信息
title: Sunmile 的小天地
description: 记录生活与技术的点滴
url: "https://sunmilechen.github.io"
baseurl: ""

# 使用 Minima 主题（关键）
theme: minima

# 显示文章摘要（推荐）
minima:
  show_excerpts: true

# 必要插件（不要删）
plugins:
  - jekyll-feed
  - jekyll-seo-tag
